### ISSUE TITLE
Could you explain the meaning of model score?

### ISSUE THREAD

**Issue by ElaineGxy** [polimi-ispl/GAN-image-detection#1]
Hi, I try your GAN-generated image detector on a query image, it outputs a score. I don't find the explanation of the score, so I wonder whether higher score is better or not.

**Comment by smandelli** [comment]
Hi @ElaineGxy,

The output score is, ideally, greater than 0 for synthetic images and lower than 0 for real images.
Please, notice that the score is not passed through Softmax function, therefore you can expect any real number, not limited to the 0-1 dynamic.

Best,
Sara

**Comment by ElaineGxy** [comment]
> Hi @ElaineGxy,
> 
> The output score is, ideally, greater than 0 for synthetic images and lower than 0 for real images. Please, notice that the score is not passed through Softmax function, therefore you can expect any real number, not limited to the 0-1 dynamic.
> 
> Best, Sara

got it, thanks~
