### ISSUE TITLE
The meaning of "score"?

### ISSUE THREAD

**Issue by SlausB** [polimi-ispl/GAN-image-detection#3]
Hello!
Sorry for such stupid question, but what "score" actually means? I guess it's not a normalized probability and sometimes goes negative. I happened to get values **-11.61**, **0.95**, **1.02**, .... Do lower (left?) values mean image being **synth** and higher mean image being **real**? What are value boundaries? Is it even possible to normalize values?
Thanks in advance!

**Comment by nicobonne** [comment]
Hi, you can take a look to [this closed issue](https://github.com/polimi-ispl/GAN-image-detection/issues/1).

**Comment by SlausB** [comment]
Got it. Thanks!
