### ISSUE TITLE
ResolvePackageNotFound

### ISSUE THREAD

**Issue by pearswick** [polimi-ispl/GAN-image-detection#4]
Apologies in advance - not a coder, and not that experienced with Powershell. I get the following error when trying to build the environment. Moving these packages under 'pip' in the .yml file doesn't seem to install them. Appreciate any guidance:

```
(base) PS D:\gan-image-detection> conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - cudatoolkit==10.2.89=hfd86e86_1
  - mkl_fft==1.1.0=py36h23d657b_0
  - xz==5.2.5=h7b6447c_0
  - mkl-service==2.3.0=py36he904b0f_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - freetype==2.10.2=h5ab3b9f_0
  - certifi==2021.5.30=py36h06a4308_0
  - python==3.6.10=h7579374_2
  - libpng==1.6.37=hbc83047_0
  - intel-openmp==2020.1=217
  - readline==8.0=h7b6447c_0
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - libgfortran-ng==7.3.0=hdf63c60_0
  - libtiff==4.1.0=h2733197_1
  - lz4-c==1.9.2=he6710b0_0
  - libedit==3.1.20181209=hc058e9b_0
  - libffi==3.3=he6710b0_1
  - tk==8.6.8=hbc83047_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - ncurses==6.2=he6710b0_1
  - jpeg==9b=h024ee3a_2
  - zlib==1.2.11=h7b6447c_3
  - pytorch==1.5.1=py3.6_cuda10.2.89_cudnn7.6.5_0
  - ca-certificates==2021.7.5=h06a4308_1
  - sqlite==3.31.1=h62c20be_1
  - ninja==1.9.0=py36hfd86e86_0
  - mkl==2020.1=217
  - openssl==1.1.1k=h27cfd23_0
  - zstd==1.4.4=h0b5b093_3
  - mkl_random==1.1.1=py36h0573a6f_0
```

**Comment by nicobonne** [comment]
Unfortunately, conda is not so good in solving enviroments expecially if they are a bit old like this one. 

I would try removing package versions for every package except for `python` and `pytorch`.
If that doesn't work, go ahead removing versions for every package. It will install latest version of packages but hopefully that won't be a big problem.

**Comment by pearswick** [comment]
Thanks @nicobonne I'll give that a shot!

**Comment by pearswick** [comment]
No luck unfortunately - if there's a newer way to do this, please let me know! Thanks

**Comment by nicobonne** [comment]
Whatever it takes to create an environment with just `pytorch`, `efficientnet` and `albumentations` should be sufficient, then you can add manually other packages if the code breaks at imports.
