### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hahahao-lh** [polimi-ispl/GAN-image-detection#6]
I have download the weights file and put them in root.when I run python gan_vs_real_detector.py --img_path $PATH_TO_TEST_IMAGE.error happened:

![1693825937531](https://github.com/polimi-ispl/GAN-image-detection/assets/68943562/9bc60444-f81b-40b1-a53c-e72d4e81fea6)
HOPE somebody can tell me why?

**Comment by nicobonne** [comment]
Be aware there is a spelling error in the zipped folder, it is called `weigths` instead of `weights`. Rename it properly and it should do the trick. I'm also renaming the folder on Dropbox so that won't happen anymore.
